### ISSUE TITLE
Usign the with_mapping=True option in bqskit.compiler() does not return a full mapping when no qubits are remapped

### ISSUE THREAD

**Issue by n-ion** [BQSKit/bqskit#253] opened 2024-06-26 03:07 UTC
When running `bqskit.compile()` with the `with_mapping=True` parameter, if the compiler does not do any qubit re-mapping or re-routing, then the returned values of `initial_mapping` and `final_mapping` appear to be `[0]`, instead of a list with length equal to the number of qubits. Would it be better to return the initial unremapped layout instead for consistency?

For example, the following circuit, when compiled with optimization level 1 or 2 does not seem to cause any re-mapping or re-routing. 

```
     ┌───┐      
q_0: ┤ X ├──────
     └─┬─┘┌────┐
q_1: ──┼──┤ √X ├
       │  └────┘
q_2: ──■────────
                
``` 
The compiler therefore returns `[0]` for both `initial_mapping` and `final_mapping` . 

However, when compiled with optimization level 4, some re-mapping occured and the compiler returned `[0, 1, 2]` for  `initial_mapping` and `[2, 1, 0]` for `final_mapping` (I assume this is only one possible remapping, it could change from run to run).

In this scenario, would it be more consistent if the returned value for `initial_mapping` and `final_mapping`  in the optimization level 1 case was just `[0, 1, 2]`?

**Comment by edyounis** [comment] 2024-06-27 16:08
Yes, definitely! Good catch. We should be returning the trivial mapping in the case where nothing is done. Is this something you would be interested in fixing?

Looking at [this line](https://github.com/BQSKit/bqskit/blob/f5abe8e700f53e06232c6e4617ba5b8d1c197d26/bqskit/compiler/passdata.py#L58), I would expect this to be the case already. It seems this is, therefore, a bug.

**Comment by edyounis** [comment] 2024-08-06 17:51
@n-ion I am not able to reproduce this on the main branch:

```python
from bqskit import Circuit
from bqskit import compile
from bqskit.ir.gates import *

c = Circuit(3)
c.append_gate(CNOTGate(), (2, 0))
c.append_gate(SXGate(), 1)
_, im, fm = compile(c, with_mapping=True)
# >>> im
# [0, 1, 2]
# >>> fm
# [0, 1, 2]
```

Do you mind sharing some small script that reproduces this issue?

**Comment by edyounis** [comment] 2024-09-11 12:22
Closing for now, feel free to re-open if the problem persists.

**Closed by edyounis** 2024-09-11 12:22 UTC
